;Configured at runtime memory and history in amount of characters:
(= (maxMemory) (empty))
(= (maxFeedback) (empty))
(= (maxRecallItems) (empty))
(= (maxHistory) (empty))

(= (initMemory)
   (progn (println! "Initializing memory")
          (configure maxFeedback 50000)
          (configure maxRecallItems 20)
          (configure maxHistory 30000)))

(= (getPrompt)
   (read-file (library mettaclaw ./memory/prompt.txt)))

(= (getMemory)
   (let $ret (read-file (library mettaclaw ./memory/STM.metta))
        (last_chars $ret (maxMemory))))

(= (getHistory)
   (let $ret (read-file (library mettaclaw ./memory/history.metta))
        (last_chars $ret (maxHistory))))

(= (addToHistory $lastmessage $response $sexpr)
   (appendToHistory ((get_time_as_string) (newline) $lastmessage (newline) $response)))

(= (appendToHistory $addition)
   (append-file (library mettaclaw ./memory/history.metta) (swrite $addition)))

(= (remember $str)
   (progn (append-file (library mettaclaw ./memory/STM.metta) (repr ((get_time_as_string) $str)))
          (let $embedding (useOpenRouterEmbedding "openai/text-embedding-3-large" (string-safe $str))
               (append-file (library mettaclaw ./memory/LTM.metta) (repr ((get_time_as_string) $str $embedding))))))

(= (query $str)
   (let* (($embedding (useOpenRouterEmbedding "openai/text-embedding-3-large" (string-safe $str)))
          ($text (read-file (library mettaclaw ./memory/LTM.metta)))
          ($atoms (parse (string_concat (string_concat "(" $text) ")"))))
        (progn (let $sorted (msort (collapse (for ($date $atom $vector) $atoms ((cosine $vector $embedding) $date $atom))))
                    (let $u (collapse (for ($sim $date $atom) (take (maxRecallItems) (reverse $sorted))
                                   ($date $atom)))
                                   (repr $u))))))
